"@context": https://schema.org
"@type": SoftwareApplication
"@id": https://github.com/cyanheads/pubchem-mcp-server

identifier: cyanheads/pubchem-mcp-server

name: PubChem MCP Server

description: >
  An MCP (Model Context Protocol) server providing comprehensive access to PubChem's vast chemical information
  database. Enables LLMs and AI agents to search, retrieve, and analyze chemical compounds, substances,
  and bioassays through the PubChem PUG REST API.

codeRepository: https://github.com/cyanheads/pubchem-mcp-server

softwareHelp:
  "@type": CreativeWork
  url: https://www.npmjs.com/package/@cyanheads/pubchem-mcp-server
  name: Documentation

maintainer:
  - "@type": Person
    name: Casey Hand
    identifier: cyanheads
    url: https://github.com/cyanheads

license: https://spdx.org/licenses/Apache-2.0.html

applicationCategory: HealthApplication

keywords:
  - PubChem

featureList:
  - PubChem

datePublished: "2025-07-14"

operatingSystem:
  - Cross-platform

programmingLanguage:
  - TypeScript
  - JavaScript
